server:
  port: 2000
  
spring:
  redis:
    port: 26379
    password: redispassword
    sentinel:
      master: mymaster
      nodes:
        - redis-sentinel
    lettuce:
      shutdown-timeout: 200ms 